#include "mpi_ll.h"

const uint32_t MPI_BLOCK_BASES[SOC_MPI_MEM_BLOCKS_NUM] = {
    RSA_MEM_X_BLOCK_BASE,
    RSA_MEM_Y_BLOCK_BASE,
    RSA_MEM_Z_BLOCK_BASE,
    RSA_MEM_M_BLOCK_BASE,
};

const uint32_t MPI_OPERATIONS_REG[SOC_MPI_OPERATIONS_NUM] = {
    RSA_MULT_START_REG,
    RSA_MOD_MULT_START_REG,
    RSA_MODEXP_START_REG,
};
